import React, { useState } from 'react';
import { GoogleGenAI } from '@google/genai';

const aspectRatios = ["1:1", "16:9", "9:16", "4:3", "3:4"];

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState('1:1');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const handleGenerate = async () => {
    if (!prompt.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: aspectRatio as "1:1" | "16:9" | "9:16" | "4:3" | "3:4",
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
            setGeneratedImage(imageUrl);
        } else {
            throw new Error("The model did not return an image.");
        }

    } catch (e) {
      setError((e as Error).message || 'An unexpected error occurred during image generation.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full">
      <h2 className="text-2xl font-bold text-neutral dark:text-gray-200 mb-4">Image Generator</h2>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">Describe the image you want to create. Powered by Imagen 4.0.</p>
      
      <div className="space-y-4">
        <div>
          <label htmlFor="prompt" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Prompt</label>
          <textarea
            id="prompt"
            rows={3}
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., A majestic lion wearing a crown, studio lighting, hyperrealistic"
            className="mt-1 w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm text-gray-900 dark:text-gray-200 focus:outline-none focus:ring-primary focus:border-primary"
            disabled={isLoading}
          />
        </div>
        <div>
          <label htmlFor="aspectRatio" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Aspect Ratio</label>
          <select
            id="aspectRatio"
            value={aspectRatio}
            onChange={(e) => setAspectRatio(e.target.value)}
            className="mt-1 block w-full pl-3 pr-10 py-2 text-base bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 focus:outline-none focus:ring-primary focus:border-primary sm:text-sm rounded-md"
            disabled={isLoading}
          >
            {aspectRatios.map(ratio => <option key={ratio} value={ratio}>{ratio}</option>)}
          </select>
        </div>
        <button onClick={handleGenerate} disabled={isLoading || !prompt.trim()} className="w-full py-2 px-4 bg-primary text-white font-semibold rounded-lg shadow-md hover:bg-primary-hover focus:outline-none focus:ring-2 focus:ring-primary focus:ring-opacity-75 disabled:bg-gray-400">
          {isLoading ? 'Generating...' : 'Generate Image'}
        </button>
      </div>

      <div className="mt-6 flex-1 flex items-center justify-center bg-gray-100 dark:bg-gray-900/50 rounded-lg p-4">
        {isLoading && <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-primary"></div>}
        {error && <p className="text-center text-red-500 bg-red-100 p-3 rounded-lg text-sm">{error}</p>}
        {generatedImage && (
          <img src={generatedImage} alt="Generated by AI" className="max-w-full max-h-full object-contain rounded-md shadow-lg" />
        )}
        {!isLoading && !error && !generatedImage && (
            <p className="text-gray-500 dark:text-gray-400">Your generated image will appear here.</p>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
